# Generated by Django 2.2.6 on 2019-12-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devdevout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_content',
            name='title',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='title',
            field=models.TextField(),
        ),
    ]
