# Generated by Django 2.2.6 on 2019-12-12 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devdevout', '0002_auto_20191212_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_content',
            name='initial_data',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='devdevout.User_Data'),
            preserve_default=False,
        ),
    ]
